"use client";
import { FormEvent, useState } from "react";
import { Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle,DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { LoadingButton } from "@/components/ui/loading-button";
import type { Priority } from "@/lib/api/types";
import { usePlanningStore } from "@/stores/planning-store";

export function NewTaskDialog({workspaceId,goalId}:{workspaceId:string;goalId?:string}){const[open,setOpen]=useState(false);const goals=usePlanningStore(s=>s.goals);const create=usePlanningStore(s=>s.createTask);const pending=usePlanningStore(s=>s.mutating);const error=usePlanningStore(s=>s.error);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);try{await create(workspaceId,{title:String(data.get("title")),description:String(data.get("description"))||undefined,goalId:String(data.get("goalId"))||undefined,priority:String(data.get("priority")) as Priority});setOpen(false);}catch{/* La boîte reste ouverte avec l'erreur du store. */}}return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger render={<Button className="bg-[#f47b64] text-[#241614]"/>}><Plus/>Nouvelle tâche</DialogTrigger><DialogContent className="border-white/10 bg-[#1b1918] p-7 text-[#f2efea]"><DialogHeader><DialogTitle>Créer une tâche</DialogTitle><DialogDescription>Décomposez un objectif en travail assignable et vérifiable.</DialogDescription></DialogHeader><form onSubmit={submit} className="grid gap-4"><fieldset disabled={pending} className="contents"><label className="grid gap-2 text-xs">Titre<Input name="title" required autoFocus/></label><label className="grid gap-2 text-xs">Description<textarea name="description" className="min-h-20 rounded-lg border border-white/10 bg-white/[.025] p-3 outline-none"/></label><label className="grid gap-2 text-xs">Objectif<select name="goalId" defaultValue={goalId??""} className="h-9 rounded-lg border border-white/10 bg-[#191715] px-3"><option value="">Sans objectif</option>{goals.map(g=><option key={g.id} value={g.id}>{g.title}</option>)}</select></label><label className="grid gap-2 text-xs">Priorité<select name="priority" defaultValue="MEDIUM" className="h-9 rounded-lg border border-white/10 bg-[#191715] px-3"><option value="LOW">Faible</option><option value="MEDIUM">Normale</option><option value="HIGH">Haute</option><option value="CRITICAL">Critique</option></select></label>{error&&<p className="text-[10px] text-red-300">{error}</p>}<LoadingButton type="submit" loading={pending} loadingText="Création…" className="bg-[#f47b64] text-[#241614]">Créer la tâche</LoadingButton></fieldset></form></DialogContent></Dialog>}
